name: "Get the sha of a tag"
description: "Get the sha of a tag"
outputs:
  githubsha:
    description: "The sha of the tag"
    value: ${{ steps.get-sha.outputs.sha }}
inputs:
  tag:
    description: "The tag"
    required: true
runs:
  using: "composite"
  steps:
    - name: Get the sha of the tag
      shell: bash
      id: sha
      run: |
        git fetch --tags
        git checkout ${{ inputs.tag }}
        echo "sha is $(git rev-parse HEAD)"
        echo "githubsha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
