name: Test checkout sha

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: "Tag"
        type: string

jobs:
  register-sha:
    runs-on: ubuntu-latest
    outputs:
      github_sha: ${{ steps.save-sha.outputs.GITHUB_SHA}}
    steps:
      - name: save sha
        id: save-sha
        run: |
          git checkout ${{ inputs.tag }}
          echo "GITHUB_SHA=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

  checkout-print:
    runs-on: ubuntu-latest
    steps:
      - name: Print sha
        env:
          GITHUB_SHA: ${{ needs.register-sha.outputs.github_sha }}
        run: |
          echo $GITHUB_SHA
