name: Test checkout sha

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: "Tag"
        type: string

jobs:
  register-sha:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Save Sha
        uses: ./.github/actions/sha-from-tag
        id: save-sha
        with:
          tag: ${{ github.event.inputs.tag }}
      - name: Print sha
        shell: bash
        run: |
          echo ${{ steps.save-sha.outputs.githubsha }}
